/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPConnectOperation */

#ifndef _Included_com_libmailcore_IMAPConnectOperation
#define _Included_com_libmailcore_IMAPConnectOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPConnectOperation_serialVersionUID
#define com_libmailcore_IMAPConnectOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
