/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_NNTPFetchOverviewOperation */

#ifndef _Included_com_libmailcore_NNTPFetchOverviewOperation
#define _Included_com_libmailcore_NNTPFetchOverviewOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_NNTPFetchOverviewOperation_serialVersionUID
#define com_libmailcore_NNTPFetchOverviewOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_NNTPFetchOverviewOperation
 * Method:    articles
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPFetchOverviewOperation_articles
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
