/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_POPDeleteMessagesOperation */

#ifndef _Included_com_libmailcore_POPDeleteMessagesOperation
#define _Included_com_libmailcore_POPDeleteMessagesOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_POPDeleteMessagesOperation_serialVersionUID
#define com_libmailcore_POPDeleteMessagesOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
