/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPFolderStatusOperation */

#ifndef _Included_com_libmailcore_IMAPFolderStatusOperation
#define _Included_com_libmailcore_IMAPFolderStatusOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPFolderStatusOperation_serialVersionUID
#define com_libmailcore_IMAPFolderStatusOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPFolderStatusOperation
 * Method:    status
 * Signature: ()Lcom/libmailcore/IMAPFolderStatus;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPFolderStatusOperation_status
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
