/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPOperation */

#ifndef _Included_com_libmailcore_IMAPOperation
#define _Included_com_libmailcore_IMAPOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPOperation_serialVersionUID
#define com_libmailcore_IMAPOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPOperation
 * Method:    errorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_IMAPOperation_errorCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
