/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_MessagePart */

#ifndef _Included_com_libmailcore_MessagePart
#define _Included_com_libmailcore_MessagePart
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_MessagePart_serialVersionUID
#define com_libmailcore_MessagePart_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
