/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_Range */

#ifndef _Included_com_libmailcore_Range
#define _Included_com_libmailcore_Range
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libmailcore_Range
 * Method:    removeRange
 * Signature: (Lcom/libmailcore/Range;)Lcom/libmailcore/IndexSet;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_Range_removeRange
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_Range
 * Method:    union
 * Signature: (Lcom/libmailcore/Range;)Lcom/libmailcore/IndexSet;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_Range_union
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_Range
 * Method:    intersection
 * Signature: (Lcom/libmailcore/Range;)Lcom/libmailcore/Range;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_Range_intersection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_Range
 * Method:    hasIntersection
 * Signature: (Lcom/libmailcore/Range;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_Range_hasIntersection
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_Range
 * Method:    leftBound
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_Range_leftBound
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_Range
 * Method:    rightBound
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_Range_rightBound
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_Range
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_Range_toString
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_Range
 * Method:    rangeWithString
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/Range;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_Range_rangeWithString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
