/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_Operation */

#ifndef _Included_com_libmailcore_Operation
#define _Included_com_libmailcore_Operation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_Operation_serialVersionUID
#define com_libmailcore_Operation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_Operation
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_Operation_cancel
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_Operation
 * Method:    isCancelled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_Operation_isCancelled
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_Operation
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_Operation_nativeStart
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
