/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_SMTPSession */

#ifndef _Included_com_libmailcore_SMTPSession
#define _Included_com_libmailcore_SMTPSession
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_SMTPSession_serialVersionUID
#define com_libmailcore_SMTPSession_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setHostname
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setHostname
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    hostname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_SMTPSession_hostname
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    port
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_SMTPSession_port
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setUsername
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setUsername
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    username
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_SMTPSession_username
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setPassword
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setPassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    password
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_SMTPSession_password
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setOAuth2Token
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setOAuth2Token
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    OAuth2Token
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_SMTPSession_OAuth2Token
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setAuthType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setAuthType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    authType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_SMTPSession_authType
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setConnectionType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setConnectionType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    connectionType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_SMTPSession_connectionType
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setTimeout
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setTimeout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    timeout
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_SMTPSession_timeout
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setCheckCertificateEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setCheckCertificateEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    isCheckCertificateEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_SMTPSession_isCheckCertificateEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setUseHeloIPEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setUseHeloIPEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    useHeloIPEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_SMTPSession_useHeloIPEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    isOperationQueueRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_SMTPSession_isOperationQueueRunning
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    cancelAllOperations
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_cancelAllOperations
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    loginOperation
 * Signature: ()Lcom/libmailcore/SMTPOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_SMTPSession_loginOperation
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    sendMessageOperation
 * Signature: ([B)Lcom/libmailcore/SMTPOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_SMTPSession_sendMessageOperation___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    sendMessageOperation
 * Signature: (Lcom/libmailcore/Address;Ljava/util/List;[B)Lcom/libmailcore/SMTPOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_SMTPSession_sendMessageOperation__Lcom_libmailcore_Address_2Ljava_util_List_2_3B
  (JNIEnv *, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    checkAccountOperation
 * Signature: (Lcom/libmailcore/Address;)Lcom/libmailcore/SMTPOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_SMTPSession_checkAccountOperation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    noopOperation
 * Signature: ()Lcom/libmailcore/SMTPOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_SMTPSession_noopOperation
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setupNative
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    finalizeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_finalizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setupNativeOperationQueueListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setupNativeOperationQueueListener
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_SMTPSession
 * Method:    setupNativeConnectionLogger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_SMTPSession_setupNativeConnectionLogger
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
