/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPQuotaOperation */

#ifndef _Included_com_libmailcore_IMAPQuotaOperation
#define _Included_com_libmailcore_IMAPQuotaOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPQuotaOperation_serialVersionUID
#define com_libmailcore_IMAPQuotaOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPQuotaOperation
 * Method:    usage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_IMAPQuotaOperation_usage
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPQuotaOperation
 * Method:    limit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_IMAPQuotaOperation_limit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
