/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_NNTPSession */

#ifndef _Included_com_libmailcore_NNTPSession
#define _Included_com_libmailcore_NNTPSession
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_NNTPSession_serialVersionUID
#define com_libmailcore_NNTPSession_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    setHostname
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_setHostname
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    hostname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_NNTPSession_hostname
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    setPort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_setPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    port
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_NNTPSession_port
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    setUsername
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_setUsername
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    username
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_NNTPSession_username
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    setPassword
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_setPassword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    password
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_NNTPSession_password
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    setConnectionType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_setConnectionType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    connectionType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_NNTPSession_connectionType
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    setTimeout
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_setTimeout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    timeout
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_NNTPSession_timeout
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    setCheckCertificateEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_setCheckCertificateEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    isCheckCertificateEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_NNTPSession_isCheckCertificateEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    isOperationQueueRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_NNTPSession_isOperationQueueRunning
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    cancelAllOperations
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_cancelAllOperations
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    fetchAllArticlesOperation
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/NNTPFetchAllArticlesOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPSession_fetchAllArticlesOperation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    fetchHeaderOperation
 * Signature: (Ljava/lang/String;I)Lcom/libmailcore/NNTPFetchHeaderOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPSession_fetchHeaderOperation
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    fetchArticleOperation
 * Signature: (Ljava/lang/String;I)Lcom/libmailcore/NNTPFetchArticleOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPSession_fetchArticleOperation
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    fetchArticleByMessageIDOperation
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/NNTPFetchArticleOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPSession_fetchArticleByMessageIDOperation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    fetchOverviewOperationWithIndexes
 * Signature: (Ljava/lang/String;Lcom/libmailcore/IndexSet;)Lcom/libmailcore/NNTPFetchOverviewOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPSession_fetchOverviewOperationWithIndexes
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    fetchServerDateOperation
 * Signature: ()Lcom/libmailcore/NNTPFetchServerTimeOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPSession_fetchServerDateOperation
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    listAllNewsgroupsOperation
 * Signature: ()Lcom/libmailcore/NNTPListNewsgroupsOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPSession_listAllNewsgroupsOperation
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    listDefaultNewsgroupsOperation
 * Signature: ()Lcom/libmailcore/NNTPListNewsgroupsOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPSession_listDefaultNewsgroupsOperation
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    disconnectOperation
 * Signature: ()Lcom/libmailcore/NNTPOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPSession_disconnectOperation
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    checkAccountOperation
 * Signature: ()Lcom/libmailcore/NNTPOperation;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPSession_checkAccountOperation
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    setupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_setupNative
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    finalizeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_finalizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    setupNativeOperationQueueListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_setupNativeOperationQueueListener
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NNTPSession
 * Method:    setupNativeConnectionLogger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NNTPSession_setupNativeConnectionLogger
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
