/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_MailException */

#ifndef _Included_com_libmailcore_MailException
#define _Included_com_libmailcore_MailException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_MailException_serialVersionUID
#define com_libmailcore_MailException_serialVersionUID -3042686055658047285LL
#undef com_libmailcore_MailException_serialVersionUID
#define com_libmailcore_MailException_serialVersionUID -3387516993124229948LL
/*
 * Class:     com_libmailcore_MailException
 * Method:    messageForErrorCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MailException_messageForErrorCode
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
