/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_HTMLRendererTemplateCallback */

#ifndef _Included_com_libmailcore_HTMLRendererTemplateCallback
#define _Included_com_libmailcore_HTMLRendererTemplateCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
