/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_NNTPFetchAllArticlesOperation */

#ifndef _Included_com_libmailcore_NNTPFetchAllArticlesOperation
#define _Included_com_libmailcore_NNTPFetchAllArticlesOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_NNTPFetchAllArticlesOperation_serialVersionUID
#define com_libmailcore_NNTPFetchAllArticlesOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_NNTPFetchAllArticlesOperation
 * Method:    articles
 * Signature: ()Lcom/libmailcore/IndexSet;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPFetchAllArticlesOperation_articles
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
