/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_AbstractMultipart */

#ifndef _Included_com_libmailcore_AbstractMultipart
#define _Included_com_libmailcore_AbstractMultipart
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_AbstractMultipart_serialVersionUID
#define com_libmailcore_AbstractMultipart_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_AbstractMultipart
 * Method:    parts
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_AbstractMultipart_parts
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_AbstractMultipart
 * Method:    setParts
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_AbstractMultipart_setParts
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
