/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPStoreLabelsOperation */

#ifndef _Included_com_libmailcore_IMAPStoreLabelsOperation
#define _Included_com_libmailcore_IMAPStoreLabelsOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPStoreLabelsOperation_serialVersionUID
#define com_libmailcore_IMAPStoreLabelsOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
