/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_Encoding */

#ifndef _Included_com_libmailcore_Encoding
#define _Included_com_libmailcore_Encoding
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_Encoding_Encoding7Bit
#define com_libmailcore_Encoding_Encoding7Bit 0L
#undef com_libmailcore_Encoding_Encoding8Bit
#define com_libmailcore_Encoding_Encoding8Bit 1L
#undef com_libmailcore_Encoding_EncodingBinary
#define com_libmailcore_Encoding_EncodingBinary 2L
#undef com_libmailcore_Encoding_EncodingBase64
#define com_libmailcore_Encoding_EncodingBase64 3L
#undef com_libmailcore_Encoding_EncodingQuotedPrintable
#define com_libmailcore_Encoding_EncodingQuotedPrintable 4L
#undef com_libmailcore_Encoding_EncodingOther
#define com_libmailcore_Encoding_EncodingOther 5L
#undef com_libmailcore_Encoding_EncodingUUEncode
#define com_libmailcore_Encoding_EncodingUUEncode -1L
#ifdef __cplusplus
}
#endif
#endif
