/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_AuthType */

#ifndef _Included_com_libmailcore_AuthType
#define _Included_com_libmailcore_AuthType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
