/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPSearchOperation */

#ifndef _Included_com_libmailcore_IMAPSearchOperation
#define _Included_com_libmailcore_IMAPSearchOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPSearchOperation_serialVersionUID
#define com_libmailcore_IMAPSearchOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPSearchOperation
 * Method:    uids
 * Signature: ()Lcom/libmailcore/IndexSet;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchOperation_uids
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
