/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPCheckAccountOperation */

#ifndef _Included_com_libmailcore_IMAPCheckAccountOperation
#define _Included_com_libmailcore_IMAPCheckAccountOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPCheckAccountOperation_serialVersionUID
#define com_libmailcore_IMAPCheckAccountOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
