/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPFolderStatus */

#ifndef _Included_com_libmailcore_IMAPFolderStatus
#define _Included_com_libmailcore_IMAPFolderStatus
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPFolderStatus_serialVersionUID
#define com_libmailcore_IMAPFolderStatus_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    setUnseenCount
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolderStatus_setUnseenCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    unseenCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_IMAPFolderStatus_unseenCount
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    setMessageCount
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolderStatus_setMessageCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    messageCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_IMAPFolderStatus_messageCount
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    setRecentCount
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolderStatus_setRecentCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    recentCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_IMAPFolderStatus_recentCount
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    setUidNext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolderStatus_setUidNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    uidNext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_IMAPFolderStatus_uidNext
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    setUidValidity
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolderStatus_setUidValidity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    uidValidity
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_IMAPFolderStatus_uidValidity
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    setHighestModSeqValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolderStatus_setHighestModSeqValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    highestModSeqValue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_IMAPFolderStatus_highestModSeqValue
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFolderStatus
 * Method:    setupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolderStatus_setupNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
