/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_NNTPOperation */

#ifndef _Included_com_libmailcore_NNTPOperation
#define _Included_com_libmailcore_NNTPOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_NNTPOperation_serialVersionUID
#define com_libmailcore_NNTPOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_NNTPOperation
 * Method:    errorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_NNTPOperation_errorCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
