/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPIdentity */

#ifndef _Included_com_libmailcore_IMAPIdentity
#define _Included_com_libmailcore_IMAPIdentity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPIdentity_serialVersionUID
#define com_libmailcore_IMAPIdentity_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    setVendor
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPIdentity_setVendor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    vendor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPIdentity_vendor
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPIdentity_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPIdentity_name
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    setVersion
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPIdentity_setVersion
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPIdentity_version
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    removeAllInfos
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPIdentity_removeAllInfos
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    allInfoKeys
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPIdentity_allInfoKeys
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    infoForKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPIdentity_infoForKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    setInfoForKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPIdentity_setInfoForKey
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_libmailcore_IMAPIdentity
 * Method:    setupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPIdentity_setupNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
