/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_PartType */

#ifndef _Included_com_libmailcore_PartType
#define _Included_com_libmailcore_PartType
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_PartType_PartTypeSingle
#define com_libmailcore_PartType_PartTypeSingle 0L
#undef com_libmailcore_PartType_PartTypeMessage
#define com_libmailcore_PartType_PartTypeMessage 1L
#undef com_libmailcore_PartType_PartTypeMultipartMixed
#define com_libmailcore_PartType_PartTypeMultipartMixed 2L
#undef com_libmailcore_PartType_PartTypeMultipartRelated
#define com_libmailcore_PartType_PartTypeMultipartRelated 3L
#undef com_libmailcore_PartType_PartTypeMultipartAlternative
#define com_libmailcore_PartType_PartTypeMultipartAlternative 4L
#ifdef __cplusplus
}
#endif
#endif
