/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPDeleteFolderOperation */

#ifndef _Included_com_libmailcore_IMAPDeleteFolderOperation
#define _Included_com_libmailcore_IMAPDeleteFolderOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPDeleteFolderOperation_serialVersionUID
#define com_libmailcore_IMAPDeleteFolderOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
