/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_SMTPNoopOperation */

#ifndef _Included_com_libmailcore_SMTPNoopOperation
#define _Included_com_libmailcore_SMTPNoopOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_SMTPNoopOperation_serialVersionUID
#define com_libmailcore_SMTPNoopOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
