/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPFetchFoldersOperation */

#ifndef _Included_com_libmailcore_IMAPFetchFoldersOperation
#define _Included_com_libmailcore_IMAPFetchFoldersOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPFetchFoldersOperation_serialVersionUID
#define com_libmailcore_IMAPFetchFoldersOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPFetchFoldersOperation
 * Method:    folders
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPFetchFoldersOperation_folders
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
