/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_POPMessageInfo */

#ifndef _Included_com_libmailcore_POPMessageInfo
#define _Included_com_libmailcore_POPMessageInfo
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_POPMessageInfo_serialVersionUID
#define com_libmailcore_POPMessageInfo_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_POPMessageInfo
 * Method:    setIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_POPMessageInfo_setIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libmailcore_POPMessageInfo
 * Method:    index
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_POPMessageInfo_index
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_POPMessageInfo
 * Method:    setSize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_POPMessageInfo_setSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_POPMessageInfo
 * Method:    size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_POPMessageInfo_size
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_POPMessageInfo
 * Method:    setUid
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_POPMessageInfo_setUid
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_POPMessageInfo
 * Method:    uid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_POPMessageInfo_uid
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_POPMessageInfo
 * Method:    setupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_POPMessageInfo_setupNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
