/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_POPNoopOperation */

#ifndef _Included_com_libmailcore_POPNoopOperation
#define _Included_com_libmailcore_POPNoopOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_POPNoopOperation_serialVersionUID
#define com_libmailcore_POPNoopOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
