/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPNamespace */

#ifndef _Included_com_libmailcore_IMAPNamespace
#define _Included_com_libmailcore_IMAPNamespace
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPNamespace_serialVersionUID
#define com_libmailcore_IMAPNamespace_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPNamespace
 * Method:    mainPrefix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPNamespace_mainPrefix
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPNamespace
 * Method:    mainDelimiter
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_libmailcore_IMAPNamespace_mainDelimiter
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPNamespace
 * Method:    prefixes
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPNamespace_prefixes
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPNamespace
 * Method:    pathForComponents
 * Signature: (Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPNamespace_pathForComponents
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_IMAPNamespace
 * Method:    pathForComponentsAndPrefix
 * Signature: (Ljava/util/List;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPNamespace_pathForComponentsAndPrefix
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPNamespace
 * Method:    componentsFromPath
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPNamespace_componentsFromPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPNamespace
 * Method:    containsFolderPath
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_IMAPNamespace_containsFolderPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPNamespace
 * Method:    namespaceWithPrefix
 * Signature: (Ljava/lang/String;C)Lcom/libmailcore/IMAPNamespace;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPNamespace_namespaceWithPrefix
  (JNIEnv *, jclass, jstring, jchar);

#ifdef __cplusplus
}
#endif
#endif
