/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPFetchNamespaceOperation */

#ifndef _Included_com_libmailcore_IMAPFetchNamespaceOperation
#define _Included_com_libmailcore_IMAPFetchNamespaceOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPFetchNamespaceOperation_serialVersionUID
#define com_libmailcore_IMAPFetchNamespaceOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPFetchNamespaceOperation
 * Method:    namespaces
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPFetchNamespaceOperation_namespaces
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
