/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPCapabilityOperation */

#ifndef _Included_com_libmailcore_IMAPCapabilityOperation
#define _Included_com_libmailcore_IMAPCapabilityOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPCapabilityOperation_serialVersionUID
#define com_libmailcore_IMAPCapabilityOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPCapabilityOperation
 * Method:    capabilities
 * Signature: ()Lcom/libmailcore/IndexSet;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPCapabilityOperation_capabilities
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
