/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_HTMLRendererTemplateCallbackUtils */

#ifndef _Included_com_libmailcore_HTMLRendererTemplateCallbackUtils
#define _Included_com_libmailcore_HTMLRendererTemplateCallbackUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    canPreviewPart
 * Signature: (Lcom/libmailcore/AbstractPart;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_canPreviewPart
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    shouldShowPart
 * Signature: (Lcom/libmailcore/AbstractPart;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_shouldShowPart
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    templateValuesForHeader
 * Signature: (Lcom/libmailcore/MessageHeader;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_templateValuesForHeader
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    templateValuesForPart
 * Signature: (Lcom/libmailcore/AbstractPart;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_templateValuesForPart
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    templateForMainHeader
 * Signature: (Lcom/libmailcore/MessageHeader;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_templateForMainHeader
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    templateForImage
 * Signature: (Lcom/libmailcore/AbstractPart;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_templateForImage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    templateForAttachment
 * Signature: (Lcom/libmailcore/AbstractPart;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_templateForAttachment
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    templateForMessage
 * Signature: (Lcom/libmailcore/AbstractMessage;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_templateForMessage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    templateForEmbeddedMessage
 * Signature: (Lcom/libmailcore/AbstractMessagePart;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_templateForEmbeddedMessage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    templateForEmbeddedMessageHeader
 * Signature: (Lcom/libmailcore/MessageHeader;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_templateForEmbeddedMessageHeader
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    templateForAttachmentSeparator
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_templateForAttachmentSeparator
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    cleanHTMLForPart
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_cleanHTMLForPart
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    filterHTMLForPart
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_filterHTMLForPart
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_HTMLRendererTemplateCallbackUtils
 * Method:    filterHTMLForMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_HTMLRendererTemplateCallbackUtils_filterHTMLForMessage
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
