/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPExpungeOperation */

#ifndef _Included_com_libmailcore_IMAPExpungeOperation
#define _Included_com_libmailcore_IMAPExpungeOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPExpungeOperation_serialVersionUID
#define com_libmailcore_IMAPExpungeOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
