/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPMessagePart */

#ifndef _Included_com_libmailcore_IMAPMessagePart
#define _Included_com_libmailcore_IMAPMessagePart
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPMessagePart_serialVersionUID
#define com_libmailcore_IMAPMessagePart_serialVersionUID 1LL
#undef com_libmailcore_IMAPMessagePart_serialVersionUID
#define com_libmailcore_IMAPMessagePart_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPMessagePart
 * Method:    setPartID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPMessagePart_setPartID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPMessagePart
 * Method:    partID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPMessagePart_partID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
