/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPFolder */

#ifndef _Included_com_libmailcore_IMAPFolder
#define _Included_com_libmailcore_IMAPFolder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPFolder_serialVersionUID
#define com_libmailcore_IMAPFolder_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPFolder
 * Method:    setPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolder_setPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPFolder
 * Method:    path
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPFolder_path
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFolder
 * Method:    setDelimiter
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolder_setDelimiter
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_libmailcore_IMAPFolder
 * Method:    delimiter
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_libmailcore_IMAPFolder_delimiter
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFolder
 * Method:    setFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolder_setFlags
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libmailcore_IMAPFolder
 * Method:    flags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_IMAPFolder_flags
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFolder
 * Method:    setupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFolder_setupNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
