/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_SMTPSendWithDataOperation */

#ifndef _Included_com_libmailcore_SMTPSendWithDataOperation
#define _Included_com_libmailcore_SMTPSendWithDataOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_SMTPSendWithDataOperation_serialVersionUID
#define com_libmailcore_SMTPSendWithDataOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
