/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_Log */

#ifndef _Included_com_libmailcore_Log
#define _Included_com_libmailcore_Log
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libmailcore_Log
 * Method:    setEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_Log_setEnabled
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_libmailcore_Log
 * Method:    isEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_Log_isEnabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
