/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPIdleOperation */

#ifndef _Included_com_libmailcore_IMAPIdleOperation
#define _Included_com_libmailcore_IMAPIdleOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPIdleOperation_serialVersionUID
#define com_libmailcore_IMAPIdleOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPIdleOperation
 * Method:    interruptIdle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPIdleOperation_interruptIdle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
