/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_POPFetchMessageOperation */

#ifndef _Included_com_libmailcore_POPFetchMessageOperation
#define _Included_com_libmailcore_POPFetchMessageOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_POPFetchMessageOperation_serialVersionUID
#define com_libmailcore_POPFetchMessageOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_POPFetchMessageOperation
 * Method:    data
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_libmailcore_POPFetchMessageOperation_data
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
