/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPIdentityOperation */

#ifndef _Included_com_libmailcore_IMAPIdentityOperation
#define _Included_com_libmailcore_IMAPIdentityOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPIdentityOperation_serialVersionUID
#define com_libmailcore_IMAPIdentityOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPIdentityOperation
 * Method:    serverIdentity
 * Signature: ()Lcom/libmailcore/IMAPIdentity;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPIdentityOperation_serverIdentity
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
