/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPMoveMessagesOperation */

#ifndef _Included_com_libmailcore_IMAPMoveMessagesOperation
#define _Included_com_libmailcore_IMAPMoveMessagesOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPMoveMessagesOperation_serialVersionUID
#define com_libmailcore_IMAPMoveMessagesOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPMoveMessagesOperation
 * Method:    uidMapping
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPMoveMessagesOperation_uidMapping
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
