/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_MessageParser */

#ifndef _Included_com_libmailcore_MessageParser
#define _Included_com_libmailcore_MessageParser
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_MessageParser_serialVersionUID
#define com_libmailcore_MessageParser_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_MessageParser
 * Method:    messageParserWithData
 * Signature: ([B)Lcom/libmailcore/MessageParser;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageParser_messageParserWithData
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_libmailcore_MessageParser
 * Method:    messageParserWithContentsOfFile
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/MessageParser;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageParser_messageParserWithContentsOfFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_MessageParser
 * Method:    mainPart
 * Signature: ()Lcom/libmailcore/AbstractPart;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageParser_mainPart
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageParser
 * Method:    data
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_libmailcore_MessageParser_data
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageParser
 * Method:    htmlRendering
 * Signature: (Lcom/libmailcore/HTMLRendererTemplateCallback;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MessageParser_htmlRendering
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageParser
 * Method:    htmlBodyRendering
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MessageParser_htmlBodyRendering
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageParser
 * Method:    plainTextRendering
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MessageParser_plainTextRendering
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageParser
 * Method:    plainTextBodyRendering
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MessageParser_plainTextBodyRendering
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libmailcore_MessageParser
 * Method:    setupNative
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageParser_setupNative
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
