/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_POPFetchMessagesOperation */

#ifndef _Included_com_libmailcore_POPFetchMessagesOperation
#define _Included_com_libmailcore_POPFetchMessagesOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_POPFetchMessagesOperation_serialVersionUID
#define com_libmailcore_POPFetchMessagesOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_POPFetchMessagesOperation
 * Method:    messages
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_POPFetchMessagesOperation_messages
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
