/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_NNTPFetchServerTimeOperation */

#ifndef _Included_com_libmailcore_NNTPFetchServerTimeOperation
#define _Included_com_libmailcore_NNTPFetchServerTimeOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_NNTPFetchServerTimeOperation_serialVersionUID
#define com_libmailcore_NNTPFetchServerTimeOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_NNTPFetchServerTimeOperation
 * Method:    time
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPFetchServerTimeOperation_time
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
