/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_ConnectionType */

#ifndef _Included_com_libmailcore_ConnectionType
#define _Included_com_libmailcore_ConnectionType
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_ConnectionType_ConnectionTypeClear
#define com_libmailcore_ConnectionType_ConnectionTypeClear 1L
#undef com_libmailcore_ConnectionType_ConnectionTypeStartTLS
#define com_libmailcore_ConnectionType_ConnectionTypeStartTLS 2L
#undef com_libmailcore_ConnectionType_ConnectionTypeTLS
#define com_libmailcore_ConnectionType_ConnectionTypeTLS 4L
#ifdef __cplusplus
}
#endif
#endif
