/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_AbstractMessage */

#ifndef _Included_com_libmailcore_AbstractMessage
#define _Included_com_libmailcore_AbstractMessage
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_AbstractMessage_serialVersionUID
#define com_libmailcore_AbstractMessage_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_AbstractMessage
 * Method:    header
 * Signature: ()Lcom/libmailcore/MessageHeader;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_AbstractMessage_header
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_AbstractMessage
 * Method:    setHeader
 * Signature: (Lcom/libmailcore/MessageHeader;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_AbstractMessage_setHeader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_AbstractMessage
 * Method:    partForContentID
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/AbstractPart;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_AbstractMessage_partForContentID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_AbstractMessage
 * Method:    partForUniqueID
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/AbstractPart;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_AbstractMessage_partForUniqueID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_AbstractMessage
 * Method:    attachments
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_AbstractMessage_attachments
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_AbstractMessage
 * Method:    htmlInlineAttachments
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_AbstractMessage_htmlInlineAttachments
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_AbstractMessage
 * Method:    requiredPartsForRendering
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_AbstractMessage_requiredPartsForRendering
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
