/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_SMTPCheckAccountOperation */

#ifndef _Included_com_libmailcore_SMTPCheckAccountOperation
#define _Included_com_libmailcore_SMTPCheckAccountOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_SMTPCheckAccountOperation_serialVersionUID
#define com_libmailcore_SMTPCheckAccountOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
