/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPSubscribeFolderOperation */

#ifndef _Included_com_libmailcore_IMAPSubscribeFolderOperation
#define _Included_com_libmailcore_IMAPSubscribeFolderOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPSubscribeFolderOperation_serialVersionUID
#define com_libmailcore_IMAPSubscribeFolderOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
