/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_NNTPFetchHeaderOperation */

#ifndef _Included_com_libmailcore_NNTPFetchHeaderOperation
#define _Included_com_libmailcore_NNTPFetchHeaderOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_NNTPFetchHeaderOperation_serialVersionUID
#define com_libmailcore_NNTPFetchHeaderOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_NNTPFetchHeaderOperation
 * Method:    header
 * Signature: ()Lcom/libmailcore/MessageHeader;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPFetchHeaderOperation_header
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
