/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPSearchExpression */

#ifndef _Included_com_libmailcore_IMAPSearchExpression
#define _Included_com_libmailcore_IMAPSearchExpression
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPSearchExpression_serialVersionUID
#define com_libmailcore_IMAPSearchExpression_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchAll
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchAll
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchFrom
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchFrom
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchTo
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchTo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchCc
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchCc
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchBcc
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchBcc
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchRecipient
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchRecipient
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchSubject
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchSubject
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchContent
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchContent
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchBody
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchBody
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchHeader
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchHeader
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchUIDs
 * Signature: (Lcom/libmailcore/IndexSet;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchUIDs
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchRead
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchRead
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchUnread
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchUnread
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchFlagged
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchFlagged
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchUnflagged
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchUnflagged
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchAnswered
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchAnswered
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchUnanswered
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchUnanswered
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchDraft
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchDraft
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchUndraft
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchUndraft
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchDeleted
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchDeleted
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchSpam
 * Signature: ()Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchSpam
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchBeforeDate
 * Signature: (Ljava/util/Date;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchBeforeDate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchOnDate
 * Signature: (Ljava/util/Date;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchOnDate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchSinceDate
 * Signature: (Ljava/util/Date;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchSinceDate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchBeforeReceivedDate
 * Signature: (Ljava/util/Date;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchBeforeReceivedDate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchOnReceivedDate
 * Signature: (Ljava/util/Date;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchOnReceivedDate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchSinceReceivedDate
 * Signature: (Ljava/util/Date;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchSinceReceivedDate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchSizeLarger
 * Signature: (J)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchSizeLarger
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchSizeSmaller
 * Signature: (J)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchSizeSmaller
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchGmailThreadID
 * Signature: (J)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchGmailThreadID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchGmailMessageID
 * Signature: (J)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchGmailMessageID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchGmailRaw
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchGmailRaw
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchAnd
 * Signature: (Lcom/libmailcore/IMAPSearchExpression;Lcom/libmailcore/IMAPSearchExpression;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchAnd
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchOr
 * Signature: (Lcom/libmailcore/IMAPSearchExpression;Lcom/libmailcore/IMAPSearchExpression;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchOr
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_libmailcore_IMAPSearchExpression
 * Method:    searchNot
 * Signature: (Lcom/libmailcore/IMAPSearchExpression;)Lcom/libmailcore/IMAPSearchExpression;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPSearchExpression_searchNot
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
