/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IndexSet */

#ifndef _Included_com_libmailcore_IndexSet
#define _Included_com_libmailcore_IndexSet
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IndexSet_serialVersionUID
#define com_libmailcore_IndexSet_serialVersionUID 1LL
#undef com_libmailcore_IndexSet_serialVersionUID
#define com_libmailcore_IndexSet_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IndexSet
 * Method:    indexSet
 * Signature: ()Lcom/libmailcore/IndexSet;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IndexSet_indexSet
  (JNIEnv *, jclass);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    indexSetWithRange
 * Signature: (Lcom/libmailcore/Range;)Lcom/libmailcore/IndexSet;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IndexSet_indexSetWithRange
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    indexSetWithIndex
 * Signature: (J)Lcom/libmailcore/IndexSet;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IndexSet_indexSetWithIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    count
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_IndexSet_count
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    addIndex
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IndexSet_addIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    removeIndex
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IndexSet_removeIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    containsIndex
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_IndexSet_containsIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    addRange
 * Signature: (Lcom/libmailcore/Range;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IndexSet_addRange
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    removeRange
 * Signature: (Lcom/libmailcore/Range;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IndexSet_removeRange
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    intersectsRange
 * Signature: (Lcom/libmailcore/Range;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IndexSet_intersectsRange
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    addIndexSet
 * Signature: (Lcom/libmailcore/IndexSet;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IndexSet_addIndexSet
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    removeIndexSet
 * Signature: (Lcom/libmailcore/IndexSet;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IndexSet_removeIndexSet
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    intersectsIndexSet
 * Signature: (Lcom/libmailcore/IndexSet;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IndexSet_intersectsIndexSet
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    allRanges
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IndexSet_allRanges
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    rangesCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_IndexSet_rangesCount
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    removeAllIndexes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IndexSet_removeAllIndexes
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IndexSet
 * Method:    setupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IndexSet_setupNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
