/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_Address */

#ifndef _Included_com_libmailcore_Address
#define _Included_com_libmailcore_Address
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_Address_serialVersionUID
#define com_libmailcore_Address_serialVersionUID 1LL
#undef com_libmailcore_Address_serialVersionUID
#define com_libmailcore_Address_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_Address
 * Method:    addressWithDisplayName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/libmailcore/Address;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_Address_addressWithDisplayName
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_libmailcore_Address
 * Method:    addressWithMailbox
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/Address;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_Address_addressWithMailbox
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_Address
 * Method:    addressWithRFC822String
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/Address;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_Address_addressWithRFC822String
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_Address
 * Method:    addressWithNonEncodedRFC822String
 * Signature: (Ljava/lang/String;)Lcom/libmailcore/Address;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_Address_addressWithNonEncodedRFC822String
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_Address
 * Method:    addressesWithRFC822String
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_Address_addressesWithRFC822String
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_Address
 * Method:    addressesWithNonEncodedRFC822String
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_Address_addressesWithNonEncodedRFC822String
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_libmailcore_Address
 * Method:    RFC822StringForAddresses
 * Signature: (Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_Address_RFC822StringForAddresses
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_Address
 * Method:    nonEncodedRFC822StringForAddresses
 * Signature: (Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_Address_nonEncodedRFC822StringForAddresses
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_libmailcore_Address
 * Method:    displayName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_Address_displayName
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_Address
 * Method:    setDisplayName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_Address_setDisplayName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_Address
 * Method:    mailbox
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_Address_mailbox
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_Address
 * Method:    setMailbox
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_Address_setMailbox
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_Address
 * Method:    RFC822String
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_Address_RFC822String
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_Address
 * Method:    nonEncodedRFC822String
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_Address_nonEncodedRFC822String
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_Address
 * Method:    setupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_Address_setupNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
