/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPAppendMessageOperation */

#ifndef _Included_com_libmailcore_IMAPAppendMessageOperation
#define _Included_com_libmailcore_IMAPAppendMessageOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPAppendMessageOperation_serialVersionUID
#define com_libmailcore_IMAPAppendMessageOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPAppendMessageOperation
 * Method:    setDate
 * Signature: (Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPAppendMessageOperation_setDate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_IMAPAppendMessageOperation
 * Method:    date
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPAppendMessageOperation_date
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPAppendMessageOperation
 * Method:    createdUID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_IMAPAppendMessageOperation_createdUID
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPAppendMessageOperation
 * Method:    finalizeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPAppendMessageOperation_finalizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPAppendMessageOperation
 * Method:    setupNativeOperationProgressListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPAppendMessageOperation_setupNativeOperationProgressListener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
