/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPPart */

#ifndef _Included_com_libmailcore_IMAPPart
#define _Included_com_libmailcore_IMAPPart
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPPart_serialVersionUID
#define com_libmailcore_IMAPPart_serialVersionUID 1LL
#undef com_libmailcore_IMAPPart_serialVersionUID
#define com_libmailcore_IMAPPart_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPPart
 * Method:    setPartID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPPart_setPartID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPPart
 * Method:    partID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPPart_partID
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPPart
 * Method:    setSize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPPart_setSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_IMAPPart
 * Method:    size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_IMAPPart_size
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPPart
 * Method:    decodedSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_libmailcore_IMAPPart_decodedSize
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPPart
 * Method:    setEncoding
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPPart_setEncoding
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libmailcore_IMAPPart
 * Method:    encoding
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_IMAPPart_encoding
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
