/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPNoopOperation */

#ifndef _Included_com_libmailcore_IMAPNoopOperation
#define _Included_com_libmailcore_IMAPNoopOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPNoopOperation_serialVersionUID
#define com_libmailcore_IMAPNoopOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
