/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPRenameFolderOperation */

#ifndef _Included_com_libmailcore_IMAPRenameFolderOperation
#define _Included_com_libmailcore_IMAPRenameFolderOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPRenameFolderOperation_serialVersionUID
#define com_libmailcore_IMAPRenameFolderOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
