/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPCopyMessagesOperation */

#ifndef _Included_com_libmailcore_IMAPCopyMessagesOperation
#define _Included_com_libmailcore_IMAPCopyMessagesOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPCopyMessagesOperation_serialVersionUID
#define com_libmailcore_IMAPCopyMessagesOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPCopyMessagesOperation
 * Method:    uidMapping
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPCopyMessagesOperation_uidMapping
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
