/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPOperationProgressListener */

#ifndef _Included_com_libmailcore_IMAPOperationProgressListener
#define _Included_com_libmailcore_IMAPOperationProgressListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
