/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_MessageHeader */

#ifndef _Included_com_libmailcore_MessageHeader
#define _Included_com_libmailcore_MessageHeader
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_MessageHeader_serialVersionUID
#define com_libmailcore_MessageHeader_serialVersionUID 1LL
#undef com_libmailcore_MessageHeader_serialVersionUID
#define com_libmailcore_MessageHeader_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    messageID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MessageHeader_messageID
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setMessageID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setMessageID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    isMessageIDAutoGenerated
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_MessageHeader_isMessageIDAutoGenerated
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    references
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_references
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setReferences
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setReferences
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    inReplyTo
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_inReplyTo
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setInReplyTo
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setInReplyTo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    date
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_date
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setDate
 * Signature: (Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setDate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    receivedDate
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_receivedDate
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setReceivedDate
 * Signature: (Ljava/util/Date;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setReceivedDate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    sender
 * Signature: ()Lcom/libmailcore/Address;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_sender
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setSender
 * Signature: (Lcom/libmailcore/Address;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setSender
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    from
 * Signature: ()Lcom/libmailcore/Address;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_from
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setFrom
 * Signature: (Lcom/libmailcore/Address;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setFrom
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    to
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_to
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setTo
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setTo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    cc
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_cc
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setCc
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setCc
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    bcc
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_bcc
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setBcc
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setBcc
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    replyTo
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_replyTo
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setReplyTo
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setReplyTo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    subject
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MessageHeader_subject
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setSubject
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setSubject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    userAgent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MessageHeader_userAgent
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setUserAgent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setUserAgent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setExtraHeader
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setExtraHeader
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    removeExtraHeader
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_removeExtraHeader
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    extraHeaderValueForName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MessageHeader_extraHeaderValueForName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    allExtraHeadersNames
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_allExtraHeadersNames
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    extractedSubject
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MessageHeader_extractedSubject
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    partialExtractedSubject
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_MessageHeader_partialExtractedSubject
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    importHeadersData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_importHeadersData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    replyHeader
 * Signature: (ZLjava/util/List;)Lcom/libmailcore/MessageHeader;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_replyHeader
  (JNIEnv *, jobject, jboolean, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    forwardHeader
 * Signature: ()Lcom/libmailcore/MessageHeader;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_MessageHeader_forwardHeader
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_MessageHeader
 * Method:    setupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_MessageHeader_setupNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
