/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_NNTPCheckAccountOperation */

#ifndef _Included_com_libmailcore_NNTPCheckAccountOperation
#define _Included_com_libmailcore_NNTPCheckAccountOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_NNTPCheckAccountOperation_serialVersionUID
#define com_libmailcore_NNTPCheckAccountOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
