/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_SMTPLoginOperation */

#ifndef _Included_com_libmailcore_SMTPLoginOperation
#define _Included_com_libmailcore_SMTPLoginOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_SMTPLoginOperation_serialVersionUID
#define com_libmailcore_SMTPLoginOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
