/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPNamespaceItem */

#ifndef _Included_com_libmailcore_IMAPNamespaceItem
#define _Included_com_libmailcore_IMAPNamespaceItem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPNamespaceItem_serialVersionUID
#define com_libmailcore_IMAPNamespaceItem_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPNamespaceItem
 * Method:    setPrefix
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPNamespaceItem_setPrefix
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPNamespaceItem
 * Method:    prefix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPNamespaceItem_prefix
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPNamespaceItem
 * Method:    setDelimiter
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPNamespaceItem_setDelimiter
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_libmailcore_IMAPNamespaceItem
 * Method:    delimiter
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_libmailcore_IMAPNamespaceItem_delimiter
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPNamespaceItem
 * Method:    pathForComponents
 * Signature: (Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPNamespaceItem_pathForComponents
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_libmailcore_IMAPNamespaceItem
 * Method:    componentsForPath
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPNamespaceItem_componentsForPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libmailcore_IMAPNamespaceItem
 * Method:    containsFolder
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libmailcore_IMAPNamespaceItem_containsFolder
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
