/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPFetchContentOperation */

#ifndef _Included_com_libmailcore_IMAPFetchContentOperation
#define _Included_com_libmailcore_IMAPFetchContentOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPFetchContentOperation_serialVersionUID
#define com_libmailcore_IMAPFetchContentOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPFetchContentOperation
 * Method:    data
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_libmailcore_IMAPFetchContentOperation_data
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFetchContentOperation
 * Method:    finalizeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFetchContentOperation_finalizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFetchContentOperation
 * Method:    setupNativeOperationProgressListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFetchContentOperation_setupNativeOperationProgressListener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
