/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPFetchParsedContentOperation */

#ifndef _Included_com_libmailcore_IMAPFetchParsedContentOperation
#define _Included_com_libmailcore_IMAPFetchParsedContentOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPFetchParsedContentOperation_serialVersionUID
#define com_libmailcore_IMAPFetchParsedContentOperation_serialVersionUID 1LL
/*
 * Class:     com_libmailcore_IMAPFetchParsedContentOperation
 * Method:    parser
 * Signature: ()Lcom/libmailcore/MessageParser;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPFetchParsedContentOperation_parser
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFetchParsedContentOperation
 * Method:    finalizeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFetchParsedContentOperation_finalizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFetchParsedContentOperation
 * Method:    setupNativeOperationProgressListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFetchParsedContentOperation_setupNativeOperationProgressListener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
